name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo snap install zig --classic --beta
            zig version
      - name: Module test
        run: zig build test
